# SITE CONFIGURATION
baseurl: 
url: "https://webdeploy.github.io"
title: Deploy Web # site's title
description: "Un sitio web de información sobre desarrollo Web" # used by search engines


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Deploy Web # blog's title
  avatar: assets/img/triangle.svg
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash

  # Header and footer text
  header_text: > #two or three lines to describe your site
     <p>Cambiar el encabezado del texto en <code>_config.yml</code> <br> para actualizar.</p>
  header_text_feature_image: assets/img/pexels/triangular.jpeg
  footer_text: >
   Desarrollado usando <a href="https://jekyllrb.com/">Jekyll</a> con <a href="https://webdeploy.github.io">Deploy Web</a>

  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: "jjmore83@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "jonathanmoreno83"
  flickr:
  gitlab:
  github: "jonathanquehay"
  google_plus: "117486954016307632346"
  instagram:
  keybase:
  linkedin:  "https://www.linkedin.com/in/jjonathanmoreno"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "jonathanquehay"
  vimeo:
  wordpress:
  youtube:
  
  # Sharing options
  share_buttons:
    facebook: true
    twitter: true
    google_plus: true
    tumblr:
    pinterest:
    pocket:
    reddit: 
    linkedin: true
    wordpress:
    email: true

  # Scripts / Features 
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  
  special_page:
    search: 
      icon: "search" # Assuming page link and icon are the same
      enabled: true
    tags:
      icon: "tags"
      enabled: true
  
  # Localization strings
  str_follow_on: "Sigueme en"
  str_rss_follow: 
  str_share_on: "Comparte en"
  str_add_to: "Agregar a"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Siguiente artículo"
  str_previous_post: "Artículo anterior"
  str_next_page: "Siguiente"
  str_previous_page: "Anterior"
  str_continue_reading: "Continue leyendo"
  str_javascript_required_disqus: "Favor habilitar JavaScript para ver los comentarios."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true
  
  
# PAGINATION
paginate: 5
paginate_path: "blog/page:num"


# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png", "package.json", "node_modules", "gulpfile.js", ".idea/*"]
